apiVersion: batch/v1
kind: CronJob
metadata:
  name: mackerel-sesame
  namespace: iot-monitor
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mackerel-sesame
              image: ghcr.io/arthur1/mackerel-sesame:0.1.0
              env:
                - name: MACKEREL_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: mackerel-arthur-1
                      key: apikey
                - name: MACKEREL_SERVICE_NAME
                  value: home
                - name: SESAME_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: sesame-api
                      key: apikey
                - name: SESAME_DEVICE_UUID
                  valueFrom:
                    secretKeyRef:
                      name: sesame-sesame5
                      key: device-uuid
                - name: SESAME_DEVICE_NAME_FOR_METRIC
                  value: sesame5
          restartPolicy: OnFailure
