on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: "/kubeconform"
          args: "-summary -output json -verbose ./manifests"
